import bgImg1 from '@/assets/images/rooms/01.png'
import bgImg2 from '@/assets/images/rooms/02.png'
import bgImg3 from '@/assets/images/rooms/03.png'

export default {
  rooms: [
    {
      id: 1,
      imgURL: bgImg1,
      title: 'lilian',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: '',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 2,
      imgURL: bgImg2,
      title: 'vegas',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: '',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 3,
      imgURL: bgImg3,
      title: 'weekendParty',
      iconNames: ['icon-calendar'],
      iconTitle: 'thu',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 4,
      imgURL: bgImg1,
      title: 'lilian',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: '',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 5,
      imgURL: bgImg2,
      title: 'vegas',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: 'pier',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 6,
      imgURL: bgImg3,
      title: 'weekendParty',
      iconNames: ['icon-calendar'],
      iconTitle: 'thu',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 7,
      imgURL: bgImg3,
      title: 'weekendParty',
      iconNames: ['icon-calendar'],
      iconTitle: 'thu',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 8,
      imgURL: bgImg1,
      title: 'lilian',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: 'pier',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 9,
      imgURL: bgImg2,
      title: 'vegas',
      iconNames: ['icon-service', 'icon-wifi', 'icon-group'],
      iconTitle: '',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
    {
      id: 10,
      imgURL: bgImg3,
      title: 'weekendParty',
      iconNames: ['icon-calendar'],
      iconTitle: 'thu',
      infoTitle: 'pier',
      infoContent: 'feel',
    },
  ],
}
